### PR TITLE
Fixed crash due to a memory leak in the logs dictionary and LogstashD…

### PR DESCRIPTION
**Pull request by nirlachman-monday**
…estination

### CODE REVIEW

**Comment by nirlachman-monday** [comment]
@gigisommo hey, can you please review?
Thanks!

**Comment by gigisommo** [comment]
Hi @nirlachman-monday, thanks for your pr. Do you have a stack trace for the crash or a way to reproduce it? I'm asking this because I didn't get what the fix is supposed to do :) Let me know!

**Comment by nirlachman-monday** [comment]
@gigisommo sure, I have plenty, but they look the same. BTW, the crash has been resolved for me now after my fix.

```
Crashed: swiftybeaver-queue-6D13818A-7AA6-4207-BE18-628C658A24D3
0  libswiftCore.dylib             0x1c60437ec swift_isUniquelyReferenced_nonNull_native + 10
1  JustLog                        0x106c65ed4 LogstashDestination.send(_:msg:thread:file:function:line:context:) + 94 (LogstashDestination.swift:94)
2  SwiftyBeaver                   0x1075ea818 closure #1 in static SwiftyBeaver.dispatch_send(level:message:thread:file:function:line:context:) + 141 (SwiftyBeaver.swift:141)
3  SwiftyBeaver                   0x1075ee564 partial apply for closure #1 in static SwiftyBeaver.dispatch_send(level:message:thread:file:function:line:context:) (<compiler-generated>)
4  SwiftyBeaver                   0x1075d0a9c thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
5  libdispatch.dylib              0x1976e8a38 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x1976e97d4 _dispatch_client_callout + 16
7  libdispatch.dylib              0x197692320 _dispatch_lane_serial_drain$VARIANT$mp + 592
8  libdispatch.dylib              0x197692e3c _dispatch_lane_invoke$VARIANT$mp + 428
9  libdispatch.dylib              0x19769b4a8 _dispatch_workloop_worker_thread + 596
10 libsystem_pthread.dylib        0x1978c9114 _pthread_wqthread + 304
11 libsystem_pthread.dylib        0x1978cbcd4 start_wqthread + 4
```

**Review by gigisommo — APPROVED** [review]
The issue is quite obscure to me, but in this way we're kind of serializing the access to the dictionary. It should not hurt and as @nirlachman-monday said. it is solving the crash that he is experincing

**Pull request merged**
