### PR TITLE
Upgrade to Swift 5 & Xcode 10.2. Upgrade SwiftyBeaver to 1.7.0

### PR DESCRIPTION
**Pull request by fguchelaar**
In order to use JustLog in Xcode 10.2 with Swift 5.0, the dependency of SwiftyBeaver needs to be upgraded. 

This PR upgrades:

* SwiftyBeaver to 1.7.0
* The Swift version to 5.0
* The project versions to Xcode 10.2

Also, I ran the tests and the example app with no issues.

### CODE REVIEW

**Comment by fguchelaar** [comment]
History repeats. Just like in #55, the CI fails, but I cannot see the details. Probably a similar issue?

**Comment by ghost** [comment]
Hi @fguchelaar, thanks for your PR.
I saw that the issue is that CI does not support or is configured to run on Xcode 10.2 and Swift 5. It looks like that is the same problem that you had with the #55. I will ask to @albertodebortoli-je and I let you know. Thank you for your contribution.

**Comment by ghost** [comment]
Thanks @fguchelaar for the contribution, the Bitrise app was created when they didn't provide support for for public apps and there is no way to turn a private into a public one.
We'll have to delete it and recreate, which is something we'll do soon.
As @luigiparpinel-je said, the failure is due to the fact the the Bitrise app uses the code 10.1, upgrading it to 10.2 w/ Swift 5 would be part of this change so that your PR could go green.

**Comment by fguchelaar** [comment]
Thanks for the feedback! In the meantime, I'll redirect my Podfile to the fork.

See you next year 👍

**Comment by ghost** [comment]
I've re-created the Bitrise app with the new stack but I can't see a way to run the job manually for branches on forks. I'll try closing and re-opening the PR and go from there. @fguchelaar

**Comment by ghost** [comment]
@fguchelaar I'm gonna merge this since it went green on the new stack. I think that Xcode 10.2 + Swift 5.0 should bring a minor version update. I'll bump to 2.6.0 in master and then publish the version to trunk.
Thanks a lot again!

**Comment by ghost** [comment]
@fguchelaar 2.6.0 has now been published to trunk 🎉

**Pull request merged**
